// Login mit Basic Authentication mit korrekten Credentials admin:123
###
# @name loginAdminCorrect
GET https://localhost/authenticate
Authorization: Basic YWRtaW46MTIz

@adminToken = {{loginAdminCorrect.response.headers.Authorization}}

### Auflisten aller Nutzer mit Token(Admin)
GET https://localhost/users
Authorization: {{adminToken}}

//
// Forum Tests
//
### Auflisten aller Foren ohne Token
GET https://localhost/forumThreads




### Auflisten aller Forumnachrichten ohne Token
https://localhost/forumMessages



// geht nicht
### Auflisten aller Forumnachrichten für Forum über nachgelagerte Suche
GET https://localhost/forumThreads/62b5e0d5fc95608f64130b50/forumMessages


// geht nicht
### Auflisten aller Forumnachrichten für Forum über nachgelagerte Suche
PUT https://localhost/forumThreads/62b5e0d5fc95608f64130b50/forumMessages


### Löschen einer Forumnachrichten
DELETE  https://localhost/forumMessages/{{forumMessageID}}
Authorization: {{adminToken}}


### Ändere die forumDescription in dem existierenden Forum
PUT https://localhost/forumThreads/62b5e0b7fc95608f64130b4f
Authorization: {{adminToken}}
Content-Type: application/json

{
    "description": "Das ist der neue Text"
}


## Ändere Forumnachricht
PUT https://localhost/forumThreads/{{forumThreadID}}
Authorization: {{adminToken}}
Content-Type: application/json

{
    "description": "Das ist der neue Text"
}
